alias: install-pytorch-kineto-from-src
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: Compiler automation
deps:
- tags: detect,os
- tags: detect,cpu
- names:
  - python
  - python3
  skip_if_env:
    MLC_CONDA_ENV:
    - 'yes'
  tags: get,python3
- tags: get,cmake
  version_min: 3.25.0
- env:
    MLC_GIT_CHECKOUT_PATH_ENV_NAME: MLC_PYTORCH_KINETO_SRC_REPO_PATH
  extra_cache_tags: pytorch-kineto,kineto,src,pytorch-kineto-src,pytorch-kineto-src-repo
  names:
  - pytorch-kineto-src-repo
  tags: get,git,repo
  update_tags_from_env_with_prefix:
    _branch.:
    - MLC_GIT_CHECKOUT
    _repo.:
    - MLC_GIT_URL
    _sha.:
    - MLC_GIT_CHECKOUT_SHA
    _tag.:
    - MLC_GIT_CHECKOUT_TAG
env:
  MLC_GIT_URL: https://github.com/pytorch/kineto
name: Build pytorch kineto from sources
new_env_keys:
- MLC_PYTORCH_KINETO_*
prehook_deps: []
sort: 1000
tags:
- install
- get
- src
- from.src
- pytorch-kineto
- kineto
- src-pytorch-kineto
uid: 98a4b061712d4483
variations:
  branch.#:
    env:
      MLC_GIT_CHECKOUT: '#'
  cuda:
    deps:
    - names:
      - cuda
      tags: get,cuda,_cudnn
    env:
      CUDA_HOME: <<<MLC_CUDA_INSTALLED_PATH>>>
      CUDA_NVCC_EXECUTABLE: <<<MLC_NVCC_BIN_WITH_PATH>>>
      CUDNN_INCLUDE_PATH: <<<MLC_CUDA_PATH_INCLUDE_CUDNN>>>
      CUDNN_LIBRARY_PATH: <<<MLC_CUDA_PATH_LIB_CUDNN>>>
      TORCH_CUDA_ARCH_LIST: Ampere Ada Hopper
      TORCH_CXX_FLAGS: -D_GLIBCXX_USE_CXX11_ABI=1
      USE_CUDA: '1'
      USE_CUDNN: '1'
  repo.#:
    env:
      MLC_GIT_URL: '#'
    group: repo
  repo.https://github.com/pytorch/kineto:
    default: true
    env:
      MLC_GIT_URL: https://github.com/pytorch/kineto
    group: repo
  sha.#:
    env:
      MLC_GIT_CHECKOUT_SHA: '#'
  tag.#:
    ad:
      pytorch-src-repo:
        tags: _full-history
    env:
      MLC_GIT_CHECKOUT_TAG: '#'
versions: {}
