alias: get-ml-model-tiny-resnet
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: AI/ML models
env:
  MLC_DOWNLOAD_FINAL_ENV_NAME: MLC_ML_MODEL_FILE_WITH_PATH
  MLC_ML_MODEL: RESNET
  MLC_ML_MODEL_DATASET: cifar-10
  MLC_ML_MODEL_IMAGE_HEIGHT: '32'
  MLC_ML_MODEL_IMAGE_WIDTH: '32'
  MLC_ML_MODEL_NORMALIZE_DATA: '0'
  MLC_ML_MODEL_RETRAINING: 'no'
  MLC_ML_MODEL_SUBTRACT_MEANS: 'YES'
  MLC_ML_MODEL_WEIGHT_TRANSFORMATIONS: 'no'
new_env_keys:
- MLC_ML_MODEL_*
prehook_deps:
- enable_if_env:
    MLC_PACKAGE_URL:
    - 'on'
  env:
    MLC_EXTRACT_EXTRACTED_FILENAME: <<<MLC_ML_MODEL_FILE>>>
  tags: download-and-extract
  force_env_keys:
    - MLC_OUTDIRNAME  
  update_tags_from_env_with_prefix:
    _url.:
    - MLC_PACKAGE_URL
print_env_at_the_end:
  MLC_ML_MODEL_FILE_WITH_PATH: Path to the ML model
tags:
- get
- raw
- ml-model
- resnet
- pretrained
- tiny
- model
- ic
- ml-model-tiny-resnet
- image-classification
uid: dd5ec11c3f6e49eb
variations:
  batch_size.#:
    env:
      MLC_ML_MODEL_BATCH_SIZE: '#'
  fp32:
    add_deps_tags:
      dependent-model:
        tags: _int8
    env:
      MLC_ML_MODEL_INPUT_DATA_TYPES: fp32
      MLC_ML_MODEL_PRECISION: fp32
      MLC_ML_MODEL_WEIGHT_DATA_TYPES: fp32
    group: precision
  int8:
    add_deps_recursive:
      dependent-model:
        tags: _int8
    default: true
    env:
      MLC_ML_MODEL_INPUT_DATA_TYPES: int8
      MLC_ML_MODEL_PRECISION: int8
      MLC_ML_MODEL_WEIGHT_DATA_TYPES: int8
    group: precision
  onnx:
    deps:
    - names:
      - python,python3
      tags: get,python3
    - names:
      - tflite-resnet-model
      - dependent-model
      tags: get,tiny,model,resnet,_tflite
    - names:
      - tf2onnx
      tags: get,generic-python-lib,_package.tf2onnx
    env:
      MLC_TMP_ML_MODEL_TF2ONNX: 'yes'
    group: framework
  tflite:
    default: true
    env:
      MLC_ML_MODEL_ACCURACY: '85'
      MLC_ML_MODEL_DATA_LAYOUT: NHWC
      MLC_ML_MODEL_FRAMEWORK: tflite
      MLC_ML_MODEL_GIVEN_CHANNEL_MEANS: ''
      MLC_ML_MODEL_INPUT_LAYERS: ''
      MLC_ML_MODEL_INPUT_LAYER_NAME: ''
      MLC_ML_MODEL_INPUT_SHAPES: ''
      MLC_ML_MODEL_NORMALIZE_DATA: '0'
      MLC_ML_MODEL_OUTPUT_LAYERS: ''
      MLC_ML_MODEL_OUTPUT_LAYER_NAME: ''
      MLC_ML_MODEL_STARTING_WEIGHTS_FILENAME: <<<MLC_PACKAGE_URL>>>
      MLC_ML_MODEL_SUBTRACT_MEANS: 'YES'
    group: framework
  tflite,int8:
    env:
      MLC_DOWNLOAD_CHECKSUM: 2d6dd48722471313e4c4528249205ae3
      MLC_PACKAGE_URL: https://github.com/mlcommons/tiny/raw/master/benchmark/training/image_classification/trained_models/pretrainedResnet_quant.tflite
  uint8:
    add_deps_tags:
      dependent-model:
        tags: _int8
    env:
      MLC_ML_MODEL_INPUT_DATA_TYPES: uint8
      MLC_ML_MODEL_PRECISION: uint8
      MLC_ML_MODEL_WEIGHT_DATA_TYPES: uint8
    group: precision
