alias: get-dataset-openimages-annotations
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: AI/ML datasets
new_env_keys:
- MLC_DATASET_OPENIMAGES_ANNOTATIONS_*
- MLC_DATASET_ANNOTATIONS_*
prehook_deps:
- env:
    MLC_DAE_FINAL_ENV_NAME: MLC_DATASET_ANNOTATIONS_FILE_PATH
  extra_cache_tags: retinanet,get,dataset-openimages-annotations
  force_cache: true
  tags: download-and-extract,_wget,_extract
  force_env_keys:
    - MLC_OUTDIRNAME  
  update_tags_from_env_with_prefix:
    _url.:
    - MLC_PACKAGE_URL
print_env_at_the_end:
  MLC_DATASET_ANNOTATIONS_FILE_PATH: Path to OpenImages annotation file
tags:
- get
- aux
- dataset-aux
- object-detection
- openimages
- annotations
uid: 47e2158ed24c44e9
variations:
  from.github:
    default: true
    env:
      MLC_DOWNLOAD_CHECKSUM: 817fd8da3aeeb0575f1e2d2926b15e68
      MLC_DOWNLOAD_FILENAME: openimages-mlperf_annotations_2.1.json.zip
      MLC_PACKAGE_URL: https://github.com/mlcommons/inference/releases/download/v2.1/openimages-mlperf_annotations_2.1.json.zip
    group: download-source
