alias: download-torrent
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: DevOps automation
default_env:
  MLC_TORRENT_WAIT_UNTIL_COMPLETED: 'no'
deps:
- tags: get,generic-sys-util,_transmission
input_description: {}
input_mapping:
  wait: MLC_TORRENT_WAIT_UNTIL_COMPLETED
new_env_keys:
- MLC_TORRENT_DOWNLOADED_PATH
- <<<MLC_TORRENT_DOWNLOADED_PATH_ENV_KEY>>>
new_state_keys: []
post_deps: []
posthook_deps: []
prehook_deps: []
tags:
- download
- torrent
- download-torrent
uid: 69b752c5618e45bb
variations:
  torrent.#:
    env:
      MLC_TORRENT_FILE: '#'
versions: {}
