alias: install-onnxruntime-from-src
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: Compiler automation
deps:
- tags: detect,os
- tags: detect,cpu
- tags: fail,filter,_windows
- names:
  - python
  - python3
  skip_if_env:
    MLC_CONDA_ENV:
    - 'yes'
  tags: get,python3
- tags: get,cmake
  version_min: 3.26.0
- tags: get,gcc
  version_max: 11.9.999
  version_max_usable: '11.0'
- env:
    MLC_GIT_CHECKOUT_PATH_ENV_NAME: MLC_ONNXRUNTIME_SRC_REPO_PATH
  extra_cache_tags: onnxruntime,src,onnxruntime-src,onnxruntime-src-repo
  names:
  - onnxruntime-src-repo
  tags: get,git,repo
  update_tags_from_env_with_prefix:
    _branch.:
    - MLC_GIT_CHECKOUT
    _repo.:
    - MLC_GIT_URL
    _sha.:
    - MLC_GIT_CHECKOUT_SHA
    _tag.:
    - MLC_GIT_CHECKOUT_TAG
env: {}
name: Build onnxruntime from sources
new_env_keys:
- MLC_ONNXRUNTIME_*
prehook_deps: []
sort: 1000
tags:
- install
- get
- src
- from.src
- onnxruntime
- src-onnxruntime
uid: 9798c7e7a5944cee
variations:
  branch.#:
    env:
      MLC_GIT_CHECKOUT: '#'
  cuda:
    deps:
    - names:
      - cuda
      tags: get,cuda,_cudnn
    env:
      MLC_ONNXRUNTIME_GPU: 'yes'
  repo.https://github.com/Microsoft/onnxruntime:
    default: true
    env:
      MLC_GIT_URL: https://github.com/Microsoft/onnxruntime
    group: repo
  sha.#:
    env:
      MLC_GIT_CHECKOUT_SHA: '#'
  tag.#:
    ad:
      onnxruntime-src-repo:
        tags: _no-recurse-submodules,_full-history
    env:
      MLC_GIT_CHECKOUT_TAG: '#'
versions: {}
