alias: get-cmake
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: Detection or installation of tools and artifacts
deps:
- tags: detect,cpu
env:
  MLC_REQUIRE_INSTALL: 'no'
new_env_keys:
- MLC_CMAKE_*
- MLC_MAKE_CORES
- +PATH
prehook_deps:
- enable_if_env:
    MLC_REQUIRE_INSTALL:
    - 'yes'
  reuse_version: true
  tags: install,cmake,prebuilt
print_env_at_the_end:
  MLC_CMAKE_BIN_WITH_PATH: Path to the tool
tags:
- get
- cmake
- get-cmake
uid: 52bf974d791b4fc8
