alias: get-dlrm
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: AI/ML models
default_env:
  MLC_GIT_DEPTH: --depth 10
  MLC_GIT_PATCH: 'no'
  MLC_GIT_URL: https://github.com/facebookresearch/dlrm.git
default_version: main
deps:
- tags: detect,os
new_env_keys:
- DLRM_DIR
tags:
- get
- src
- dlrm
uid: 63680ac2449a4241
variations:
  full-history:
    env:
      MLC_GIT_DEPTH: ''
versions:
  main:
    env:
      MLC_GIT_CHECKOUT: main
