alias: get-dataset-squad-vocab
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: AI/ML datasets
new_env_keys:
- MLC_ML_MODEL_BERT_VOCAB_FILE_WITH_PATH
- MLC_DATASET_SQUAD_VOCAB_PATH
prehook_deps:
- env:
    MLC_DOWNLOAD_FINAL_ENV_NAME: MLC_DATASET_SQUAD_VOCAB_PATH
  extra_cache_tags: bert,get,dataset-squad-vocab
  force_cache: true
  tags: download-and-extract,_wget
  force_env_keys:
    - MLC_OUTDIRNAME  
  update_tags_from_env_with_prefix:
    _url.:
    - MLC_PACKAGE_URL
print_env_at_the_end:
  MLC_DATASET_SQUAD_VOCAB_PATH: Path to SQUAD vocab file
tags:
- get
- aux
- squad
- dataset-aux
- language-processing
- squad-aux
- vocab
- squad-vocab
uid: e38874fff5094577
variations:
  from.zenodo:
    default: true
    env:
      MLC_DOWNLOAD_CHECKSUM: 64800d5d8528ce344256daf115d4965e
      MLC_DOWNLOAD_FILENAME: vocab.txt
      MLC_PACKAGE_URL: https://zenodo.org/record/3733868/files/vocab.txt
    group: download-source
