alias: get-java
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: Detection or installation of tools and artifacts
default_env:
  MLC_JAVA_PREBUILT_BUILD: '36'
  MLC_JAVA_PREBUILT_FILENAME: openjdk-${MLC_JAVA_PREBUILT_VERSION}+${MLC_JAVA_PREBUILT_BUILD}_${MLC_JAVA_PREBUILT_HOST_OS}-x64_bin
  MLC_JAVA_PREBUILT_URL: https://download.java.net/openjdk/jdk${MLC_JAVA_PREBUILT_VERSION}/ri/
  MLC_JAVA_PREBUILT_VERSION: '19'
deps:
- tags: detect,os
input_mapping:
  install: MLC_JAVA_PREBUILT_INSTALL
new_env_keys:
- MLC_JAVA_*
- JAVA_HOME
- +PATH
tags:
- get
- java
uid: 9399d0e785704f8c
variations:
  install:
    env:
      MLC_JAVA_PREBUILT_INSTALL: 'on'
