alias: get-dataset-imagenet-train
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: AI/ML datasets
deps: []
input_description: {}
input_mapping:
  input: IMAGENET_TRAIN_PATH
  torrent: MLC_DATASET_IMAGENET_TRAIN_TORRENT_PATH
new_env_keys:
- MLC_DATASET_PATH
- MLC_DATASET_IMAGENET_*
new_state_keys: []
post_deps: []
posthook_deps: []
prehook_deps:
- enable_if_env:
    MLC_DATASET_IMAGENET_VAL_REQUIRE_DAE:
    - 'yes'
    - 'True'
  env:
    MLC_EXTRACT_TO_FOLDER: imagenet-2012-train
  tags: download-and-extract,file,_extract
  update_tags_from_env:
  - MLC_DAE_EXTRA_TAGS
  update_tags_from_env_with_prefix:
    _url.:
    - MLC_DAE_URL
- enable_if_env:
    MLC_DAE_ONLY_EXTRACT:
    - 'yes'
    - 'True'
  env:
    MLC_EXTRACT_TO_FOLDER: imagenet-2012-train
  tags: file,extract
  update_tags_from_env_with_prefix:
    _path.:
    - MLC_EXTRACT_PATH
tags:
- get
- imagenet
- train
- dataset
- original
uid: 2bec165da5cc4ebf
variations: {}
versions: {}
