alias: prepare-training-data-resnet
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: MLPerf benchmark support
deps:
- names:
  - imagenet-train
  tags: get,dataset,imagenet,train
- names:
  - imagenet-val
  tags: get,dataset,imagenet,val,original,_full
- tags: get,generic-sys-util,_rsync
input_description: {}
input_mapping:
  data_dir: MLC_DATA_DIR
new_env_keys:
- MLC_MLPERF_TRAINING_RESNET_*
- MLC_MLPERF_TRAINING_NVIDIA_RESNET_PREPROCESSED_PATH
new_state_keys: []
post_deps: []
posthook_deps: []
prehook_deps:
- env:
    MLC_DOWNLOAD_CHECKSUM: ''
    MLC_DOWNLOAD_FINAL_ENV_NAME: MLC_IMAGENET_LABELS_FILE_PATH
    MLC_DOWNLOAD_PATH: <<<MLC_IMAGENET_LABELS_DOWNLOAD_DIR>>>
    MLC_DOWNLOAD_RENAME_FILE: synset_labels.txt
  extra_cache_tags: imagenet,val,labels
  force_cache: true
  tags: download,file,_wget,_url.https://raw.githubusercontent.com/tensorflow/models/master/research/slim/datasets/imagenet_2012_validation_synset_labels.txt
- enable_if_env:
    MLC_TMP_VARIATION:
    - reference
  env:
    MLC_DOWNLOAD_FINAL_ENV_NAME: MLC_IMAGENET_TO_GCS_SCRIPT_PATH
  extra_cache_tags: imagenet_to_gcs,script
  force_cache: true
  tags: download,file,_wget,_url.https://raw.githubusercontent.com/tensorflow/tpu/master/tools/datasets/imagenet_to_gcs.py
tags:
- prepare
- mlperf
- training
- data
- input
- resnet
uid: d42a8a8ca2704f9f
variations:
  mxnet.#:
    env:
      MLC_MXNET_VERSION: '#'
  nvidia:
    default: true
    deps:
    - names:
      - nvidia-training-code
      tags: get,mlperf,training,nvidia,code
    - env:
        MLC_GIT_CHECKOUT_PATH_ENV_NAME: MLC_NVIDIA_DEEPLEARNING_EXAMPLES_REPO_PATH
      extra_cache_tags: nvidia,deeplearning_examples
      tags: get,git,repo,_repo.https://github.com/NVIDIA/DeepLearningExamples,_sha.81ee705868a11d6fe18c12d237abe4a08aab5fd6
    env:
      MLC_TMP_VARIATION: nvidia
    group: implementation
  reference:
    deps:
    - names:
      - mlperf-training-src
      tags: get,mlperf,training,src
    - names:
      - python3
      tags: get,python3
    - tags: get,generic-python-lib,_tensorflow
    - tags: get,generic-python-lib,_protobuf
    env:
      MLC_TMP_VARIATION: reference
    group: implementation
versions: {}
