alias: get-mlperf-tiny-src
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: MLPerf benchmark support
default_env:
  MLC_GIT_CHECKOUT: master
  MLC_GIT_PATCH: 'no'
  MLC_GIT_RECURSE_SUBMODULES: ''
  MLC_GIT_URL: https://github.com/mlcommons/tiny.git
deps:
- tags: detect,os
- names:
  - python
  - python3
  tags: get,python3
new_env_keys:
- MLC_MLPERF_TINY_*
- +PYTHONPATH
tags:
- get
- src
- source
- tiny
- tiny-src
- tiny-source
- tinymlperf
- tinymlperf-src
- mlperf
- mlcommons
uid: 777843a0bb034524
