alias: get-ml-model-rnnt
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: AI/ML models
env:
  MLC_ML_MODEL: rnnt
  MLC_ML_MODEL_DATASET: librispeech
  MLC_ML_MODEL_RETRAINING: 'no'
  MLC_ML_MODEL_WEIGHT_TRANSFORMATIONS: 'no'
new_env_keys:
- MLC_ML_MODEL_*
print_env_at_the_end:
  MLC_ML_MODEL_FILE_WITH_PATH: Path to the ML model
tags:
- get
- ml-model
- rnnt
- raw
- librispeech
- speech-recognition
uid: 8858f18b89774d28
variations:
  amazon-s3:
    group: download-src
  fp32:
    default: true
    env:
      MLC_ML_MODEL_INPUT_DATA_TYPES: fp32
      MLC_ML_MODEL_PRECISION: fp32
      MLC_ML_MODEL_WEIGHT_DATA_TYPES: fp32
    group: precision
  pytorch:
    default: true
    env:
      MLC_ML_MODEL_FRAMEWORK: pytorch
    group: framework
  pytorch,fp32:
    env:
      MLC_ML_MODEL_ACCURACY: '0.07452253714852645'
      MLC_PACKAGE_URL: https://zenodo.org/record/3662521/files/DistributedDataParallel_1576581068.9962234-epoch-100.pt?download=1
  pytorch,fp32,amazon-s3:
    env: {}
  pytorch,fp32,zenodo:
    env:
      MLC_PACKAGE_URL: https://zenodo.org/record/3662521/files/DistributedDataParallel_1576581068.9962234-epoch-100.pt?download=1
  weights:
    env:
      MLC_MODEL_WEIGHTS_FILE: 'yes'
  zenodo:
    default: true
    group: download-src
