alias: install-opencv-from-src
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: Compiler automation
deps:
- tags: detect,os
- tags: detect,cpu
- env:
    MLC_GIT_CHECKOUT_PATH_ENV_NAME: MLC_OPENCV_SRC_REPO_PATH
  extra_cache_tags: opencv,src,opencv-src,opencv-src-repo
  names:
  - opencv-src-repo
  - opencv-src
  tags: get,git,repo
  update_tags_from_env_with_prefix:
    _branch.:
    - MLC_GIT_CHECKOUT
    _repo.:
    - MLC_GIT_URL
    _sha.:
    - MLC_GIT_CHECKOUT_SHA
    _tag.:
    - MLC_GIT_CHECKOUT_TAG
env:
  MLC_GIT_URL: https://github.com/opencv/opencv
name: Build opencv from sources
new_env_keys:
- MLC_OPENCV_*
prehook_deps: []
sort: 1000
tags:
- install
- get
- src
- from.src
- opencv
- opencv
- src-opencv
uid: 98552486a0bc4214
variations:
  branch.#:
    env:
      MLC_GIT_CHECKOUT: '#'
  repo.#:
    env:
      MLC_GIT_URL: '#'
    group: repo
  repo.https://github.com/opencv/opencv:
    default: true
    env:
      MLC_GIT_URL: https://github.com/opencv/opencv
    group: repo
  sha.#:
    env:
      MLC_GIT_CHECKOUT_SHA: '#'
  tag.#:
    ad:
      opencv-src-repo:
        tags: _no-recurse-submodules,_full-history
    env:
      MLC_GIT_CHECKOUT_TAG: '#'
versions: {}
