alias: get-go
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: Compiler automation
clean_files: []
env:
  MLC_REQUIRE_INSTALL: 'no'
new_env_keys:
- MLC_GO_*
- +PATH
prehook_deps:
- enable_if_env:
    MLC_REQUIRE_INSTALL:
    - 'yes'
  reuse_version: true
  tags: install,go
tags:
- get
- tool
- go
- get-go
uid: ab42647a96724a25
