alias: get-mlperf-tiny-eembc-energy-runner-src
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: MLPerf benchmark support
default_env:
  MLC_GIT_CHECKOUT: main
  MLC_GIT_PATCH: 'no'
  MLC_GIT_RECURSE_SUBMODULES: ''
  MLC_GIT_URL: https://github.com/eembc/energyrunner
new_env_keys:
- MLC_EEMBC_ENERGY_RUNNER_*
- +PYTHONPATH
tags:
- get
- src
- source
- eembc
- energyrunner
- energy-runner
- eembc-energy-runner
- tinymlperf-energy-runner
uid: c7da8d1ce4164a4b
