alias: get-dataset-cnndm
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: AI/ML datasets
default_env:
  MLC_DATASET_CALIBRATION: 'no'
deps:
- tags: get,sys-utils-cm
- names:
  - python
  - python3
  tags: get,python3
  version_max: 3.9.999
- names:
  - inference-src
  skip_if_env:
    MLC_CNNDM_INTEL_VARIATION:
    - 'yes'
  tags: mlperf,inference,source
- tags: get,generic-python-lib,_package.simplejson
- tags: get,generic-python-lib,_datasets
- tags: get,generic-python-lib,_package.tokenizers
- tags: get,generic-python-lib,_numpy
env:
  MLC_DATASET: CNNDM
tags:
- get
- dataset
- gpt-j
- cnndm
- cnn-dailymail
- original
uid: aed298c156e24257
variations:
  calibration:
    env:
      MLC_DATASET_CALIBRATION: 'yes'
    group: dataset-type
    new_env_keys:
    - MLC_CALIBRATION_DATASET_PATH
    - MLC_CALIBRATION_DATASET_CNNDM_PATH
  intel: {}
  intel,validation:
    env:
      MLC_CNNDM_INTEL_VARIATION: 'yes'
  validation:
    default: true
    env:
      MLC_DATASET_CALIBRATION: 'no'
    group: dataset-type
    new_env_keys:
    - MLC_DATASET_PATH
    - MLC_DATASET_EVAL_PATH
    - MLC_DATASET_CNNDM_EVAL_PATH
