alias: get-ml-model-bert-base-squad
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: AI/ML models
env:
  MLC_ML_MODEL: BERT
  MLC_ML_MODEL_DATASET: squad-1.1
  MLC_ML_MODEL_MAX_SEQ_LENGTH: '384'
  MLC_ML_MODEL_NAME: MLPERF BERT Base on SQuAD v1.1
  MLC_TMP_ML_MODEL_REQUIRE_DOWNLOAD: 'no'
new_env_keys:
- MLC_ML_MODEL*
post_deps:
- tags: get,bert,squad,vocab
prehook_deps:
- enable_if_env:
    MLC_TMP_ML_MODEL_REQUIRE_DOWNLOAD: 'yes'
  env:
    MLC_DOWNLOAD_FINAL_ENV_NAME: MLC_ML_MODEL_FILE_WITH_PATH
    MLC_EXTRACT_EXTRACTED_FILENAME: <<<MLC_ML_MODEL_FILE>>>
    MLC_EXTRACT_FINAL_ENV_NAME: MLC_ML_MODEL_FILE_WITH_PATH
  tags: download-and-extract
  update_tags_from_env_with_prefix:
    _url.:
    - MLC_PACKAGE_URL
print_env_at_the_end:
  MLC_ML_MODEL_BERT_VOCAB_FILE_WITH_PATH: Path to the BERT vocab file
  MLC_ML_MODEL_FILE_WITH_PATH: Path to the ML model
tags:
- get
- ml-model
- raw
- bert
- bert-base
- bert-squad
- language
- language-processing
uid: b3b10b452ce24c5f
variations:
  deepsparse:
    env:
      MLC_ML_MODEL_FRAMEWORK: deepsparse
      MLC_ML_MODEL_INPUT_IDS_NAME: input_ids
      MLC_ML_MODEL_INPUT_MASK_NAME: input_mask
      MLC_ML_MODEL_INPUT_SEGMENTS_NAME: segment_ids
      MLC_ML_MODEL_OUTPUT_END_LOGITS_NAME: output_end_logits
      MLC_ML_MODEL_OUTPUT_START_LOGITS_NAME: output_start_logits
    group: framework
  deepsparse,int8:
    deps:
    - names:
      - neural-magic-zoo-downloader
      tags: get,ml-model,zoo,deepsparse,_bert-base-pruned95_obs_quant-none
    env:
      MLC_ML_MODEL_F1: '87.89'
      MLC_ML_MODEL_FILE: model.onnx
      MLC_PRUNING_PERCENTAGE: '95'
  fp32:
    default: true
    env:
      MLC_ML_MODEL_PRECISION: fp32
    group: precision
  int8:
    env:
      MLC_ML_MODEL_PRECISION: int8
      MLC_ML_MODEL_QUANTIZED: 'yes'
    group: precision
