alias: calibrate-model-for.qaic
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: AI/ML optimization
deps:
- tags: detect,cpu
- names:
  - qaic-apps-sdk
  tags: get,qaic,apps,sdk
- enable_if_env:
    MLC_CALIBRATE_OPENIMAGES:
    - 'yes'
  names:
  - openimages-cal
  - preprocessed-dataset
  tags: get,preprocessed,dataset,_calibration,openimages,_for.retinanet.onnx,_NCHW,_fp32,_custom-annotations
- enable_if_env:
    MLC_CALIBRATE_IMAGENET:
    - 'yes'
  names:
  - imagenet-cal
  - preprocessed-calibration-dataset
  tags: get,dataset,imagenet,preprocessed,_calibration,_for.resnet50,_float32,_rgb32
- enable_if_env:
    MLC_CALIBRATE_SQUAD:
    - 'on'
  names:
  - squad-cal
  - preprocessed-dataset
  tags: get,dataset,preprocessed,_calib1,squad,_pickle,_seq-length.384,_packed
- names:
  - model-src
  tags: get,ml-model
new_env_keys:
- MLC_QAIC_MODEL_PROFILE_*
tags:
- qaic
- calibrate
- profile
- qaic-profile
- qaic-calibrate
uid: 817bad70df2f4e45
variations:
  bert-99:
    base:
    - bert_
    env:
      MLC_CALIBRATE_SQUAD: 'yes'
      MLC_QAIC_COMPILER_ARGS: ''
      MLC_QAIC_COMPILER_PARAMS: -onnx-define-symbol=batch_size,1 -onnx-define-symbol=seg_length,<<<MLC_DATASET_SQUAD_TOKENIZED_MAX_SEQ_LENGTH>>>
        -input-list-file=<<<MLC_DATASET_SQUAD_TOKENIZED_PACKED_FILENAMES_FILE>>> -num-histogram-bins=512
        -profiling-threads=<<<MLC_HOST_CPU_PHYSICAL_CORES_PER_SOCKET>>>
      MLC_QAIC_MODEL_TO_CONVERT: calibrate_bert_mlperf
    group: model
  bert_:
    adr:
      model-src:
        tags: bert-large,_onnx,_packed
    default-variations:
      seq-length: seq.384
    env:
      MLC_CREATE_INPUT_BATCH: 'no'
      MLC_QAIC_MODEL_NAME: bert-large
  bs.#:
    env:
      MLC_CREATE_INPUT_BATCH: 'yes'
      MLC_QAIC_MODEL_BATCH_SIZE: '#'
    group: batch-size
  bs.1:
    env:
      MLC_CREATE_INPUT_BATCH: 'yes'
      MLC_QAIC_MODEL_BATCH_SIZE: '1'
    group: batch-size
  filter-size.#:
    ad:
      preprocessed-dataset:
        tags: _filter-size.#,_filter,_size.#
    group: calib-dataset-filter-size
  first.#:
    adr:
      preprocessed-dataset:
        tags: first.#
  mlperf.option1:
    adr:
      preprocessed-dataset:
        tags: _mlperf.option1
    group: calibration-option
  mlperf.option2:
    adr:
      preprocessed-dataset:
        tags: _mlperf.option2
    group: calibration-option
  resnet50:
    adr:
      model-src:
        tags: resnet50,_tf
    default_variations:
      calibration-option: mlperf.option1
      model-framework: tf
    env:
      MLC_CALIBRATE_IMAGENET: 'yes'
      MLC_QAIC_COMPILER_ARGS: ''
      MLC_QAIC_COMPILER_PARAMS: -output-node-name=ArgMax -profiling-threads=<<<MLC_HOST_CPU_PHYSICAL_CORES_PER_SOCKET>>>
      MLC_QAIC_MODEL_NAME: resnet50
      MLC_QAIC_MODEL_TO_CONVERT: calibrate_resnet50_tf
      MLC_QAIC_OUTPUT_NODE_NAME: -output-node-name=ArgMax
    group: model
  resnet50,tf:
    adr:
      model-src:
        tags: _fix-input-shape
      preprocessed-dataset:
        tags: _NHWC
    env:
      MLC_QAIC_MODEL_TO_CONVERT: calibrate_resnet50_tf
  retinanet:
    adr:
      model-src:
        tags: retinanet,_no-nms,_onnx
    env:
      MLC_CALIBRATE_OPENIMAGES: 'yes'
      MLC_QAIC_COMPILER_ARGS: ''
      MLC_QAIC_COMPILER_PARAMS: -enable-channelwise -profiling-threads=<<<MLC_HOST_CPU_PHYSICAL_CORES_PER_SOCKET>>>
        -onnx-define-symbol=batch_size,<<<MLC_QAIC_MODEL_BATCH_SIZE>>> -node-precision-info=<<<MLC_ML_MODEL_RETINANET_QAIC_NODE_PRECISION_INFO_FILE_PATH>>>
      MLC_QAIC_MODEL_NAME: retinanet
      MLC_QAIC_MODEL_TO_CONVERT: calibrate_retinanet_no_nms_mlperf
    group: model
    new_env_keys:
    - MLC_QAIC_MODEL_RETINANET_*
  seq.#:
    ad:
      squad-preprocessed:
        tags: _seq.#
    env:
      MLC_DATASET_SQUAD_TOKENIZED_MAX_SEQ_LENGTH: '#'
    group: seq-length
  seq.384:
    ad:
      squad-preprocessed:
        tags: _seq.384
    env:
      MLC_DATASET_SQUAD_TOKENIZED_MAX_SEQ_LENGTH: '#'
    group: seq-length
  tf:
    group: model-framework
