alias: get-dataset-kits19
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: AI/ML datasets
default_env:
  MLC_GIT_CHECKOUT: master
  MLC_GIT_DEPTH: --depth 2
  MLC_GIT_PATCH: 'no'
  MLC_GIT_RECURSE_SUBMODULES: ''
  MLC_GIT_URL: https://github.com/neheller/kits19
default_version: master
deps:
- tags: detect,os
- names:
  - python3
  - python
  tags: get,python3
new_env_keys:
- MLC_DATASET_*
tags:
- get
- dataset
- medical-imaging
- kits
- original
- kits19
uid: 79992bb221024ac5
variations:
  calibration:
    env:
      MLC_DATASET_CALIBRATION: 'yes'
  default:
    base:
    - short-history
    env:
      MLC_GIT_PATCH: 'no'
  full-history:
    env:
      MLC_GIT_DEPTH: ''
  no-recurse-submodules:
    env:
      MLC_GIT_RECURSE_SUBMODULES: ''
  patch:
    env:
      MLC_GIT_PATCH: 'yes'
  short-history:
    env:
      MLC_GIT_DEPTH: --depth 5
  validation:
    env:
      MLC_DATASET_VALIDATION: 'yes'
versions:
  custom:
    env:
      MLC_GIT_CHECKOUT: ''
      MLC_GIT_SHA: 'yes'
  master:
    env:
      MLC_GIT_CHECKOUT: master
