alias: get-javac
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: Detection or installation of tools and artifacts
default_env:
  MLC_JAVAC_PREBUILT_BUILD: '36'
  MLC_JAVAC_PREBUILT_FILENAME: openjdk-${MLC_JAVAC_PREBUILT_VERSION}+${MLC_JAVAC_PREBUILT_BUILD}_${MLC_JAVAC_PREBUILT_HOST_OS}-x64_bin
  MLC_JAVAC_PREBUILT_URL: https://download.java.net/openjdk/jdk${MLC_JAVAC_PREBUILT_VERSION}/ri/
  MLC_JAVAC_PREBUILT_VERSION: '19'
deps:
- tags: detect,os
input_mapping:
  install: MLC_JAVAC_PREBUILT_INSTALL
new_env_keys:
- MLC_JAVAC_*
- MLC_JAVA_*
- JAVA_HOME
- +PATH
tags:
- get
- javac
uid: 509280c497b24226
variations:
  install:
    env:
      MLC_JAVAC_PREBUILT_INSTALL: 'on'
