alias: get-dataset-criteo
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: AI/ML datasets
default_env:
  MLC_BACKUP_ZIPS: 'no'
env:
  MLC_DATASET: terabyte
input_mapping:
  criteo_path: MLC_CRITEO_PATH
new_env_keys:
- MLC_DATASET*
tags:
- get
- dataset
- criteo
- original
uid: 194a47d908714897
variations:
  backup:
    env:
      MLC_BACKUP_ZIPS: 'yes'
  fake:
    env:
      MLC_CRITEO_FAKE: 'yes'
