alias: get-ml-model-3d-unet-kits19
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: AI/ML models
env:
  MLC_ML_MODEL: 3d-unet-kits19
  MLC_ML_MODEL_DATASET: kits19
  MLC_ML_MODEL_RETRAINING: 'no'
  MLC_ML_MODEL_WEIGHT_TRANSFORMATIONS: 'no'
new_env_keys:
- MLC_ML_MODEL_*
print_env_at_the_end:
  MLC_ML_MODEL_FILE_WITH_PATH: Path to the ML model
tags:
- get
- ml-model
- raw
- 3d-unet
- kits19
- medical-imaging
uid: fb7e31419c0f4226
variations:
  fp32:
    default: true
    env:
      MLC_ML_MODEL_INPUT_DATA_TYPES: fp32
      MLC_ML_MODEL_PRECISION: fp32
      MLC_ML_MODEL_WEIGHT_DATA_TYPES: fp32
    group: precision
  onnx:
    default: true
    env:
      MLC_ML_MODEL_FRAMEWORK: onnx
    group: framework
  onnx,fp32:
    deps:
    - env:
        MLC_DOWNLOAD_CHECKSUM: 82f0618fde78f9839e7c712274019b4a
        MLC_DOWNLOAD_FILENAME: 3dunet_kits19_128x128x128_dynbatch.onnx
        MLC_DOWNLOAD_FINAL_ENV_NAME: MLC_ML_MODEL_FILE_WITH_PATH
        MLC_DOWNLOAD_URL: https://zenodo.org/record/5597155/files/3dunet_kits19_128x128x128_dynbatch.onnx?download=1
      extra_cache_tags: 3d-unet,medical-imaging
      force-cache: true
      tags: download,file,download-file,_wget
      force_env_keys:
        - MLC_OUTDIRNAME
    env:
      MLC_ML_MODEL_ACCURACY: '0.86170'
      MLC_ML_MODEL_FILE: 3dunet_kits19_128x128x128_dynbatch.onnx
  pytorch:
    env:
      MLC_ML_MODEL_FRAMEWORK: pytorch
    group: framework
  pytorch,fp32:
    deps:
    - env:
        MLC_DOWNLOAD_CHECKSUM: 2251109371f408c9f10a4320ffdcaef8
        MLC_DOWNLOAD_FILENAME: 3dunet_kits19_pytorch.ptc
        MLC_DOWNLOAD_FINAL_ENV_NAME: MLC_ML_MODEL_FILE_WITH_PATH
        MLC_DOWNLOAD_URL: https://zenodo.org/record/5597155/files/3dunet_kits19_pytorch.ptc?download=1
      extra_cache_tags: 3d-unet,medical-imaging
      force-cache: true
      tags: download,file,download-file,_wget
      force_env_keys:
        - MLC_OUTDIRNAME
    env:
      MLC_ML_MODEL_ACCURACY: '0.86170'
      MLC_ML_MODEL_FILE: 3dunet_kits19_pytorch.ptc
  pytorch,fp32,weights:
    deps:
    - env:
        MLC_DAE_FINAL_ENV_NAME: MLC_ML_MODEL_FILE_WITH_PATH
        MLC_DAE_URL: https://zenodo.org/record/5597155/files/3dunet_kits19_pytorch_checkpoint.pth?download=1
        MLC_DOWNLOAD_CHECKSUM: 09c696e3ec13d83c628498bcd831eb5b
        MLC_DOWNLOAD_FILENAME: 3dunet_kits19_pytorch_checkpoint.pth
      extra_cache_tags: 3d-unet,medical-imaging
      force-cache: true
      tags: download-and-extract,_wget,_extract
      force_env_keys:
        - MLC_OUTDIRNAME
    env:
      MLC_ML_MODEL_ACCURACY: '0.86170'
      MLC_ML_MODEL_FILE: 3dunet_kits19_pytorch_checkpoint.pth
  tensorflow:
    alias: tf
  tf:
    env:
      MLC_ML_MODEL_FRAMEWORK: tensorflow
    group: framework
  tf,fp32:
    deps:
    - env:
        MLC_DAE_FINAL_ENV_NAME: MLC_ML_MODEL_FILE_WITH_PATH
        MLC_DAE_URL: https://zenodo.org/record/5597155/files/3dunet_kits19_128x128x128.tf.zip?download=1
        MLC_DOWNLOAD_CHECKSUM: 9497108bd0504ae8f85a764a807b76a9
        MLC_DOWNLOAD_FILENAME: 3dunet_kits19_128x128x128.tf.zip
      extra_cache_tags: 3d-unet,medical-imaging
      force-cache: true
      tags: download-and-extract,_wget,_extract
      force_env_keys:
        - MLC_OUTDIRNAME
    env:
      MLC_ML_MODEL_ACCURACY: '0.86170'
      MLC_ML_MODEL_FILE: 3dunet_kits19_128x128x128.tf
  weights:
    env:
      MLC_MODEL_WEIGHTS_FILE: 'yes'
