alias: get-cuda
uid: 46d133d9ef92422d

automation_alias: script
automation_uid: 5b4e0237da074764

tags:
- get
- cuda
- cuda-compiler
- cuda-lib
- toolkit
- lib
- nvcc
- get-nvcc
- get-cuda
- 46d133d9ef92422d

cache: true

category: CUDA automation

default_env:
  MLC_CUDA_PATH_LIB_CUDNN_EXISTS: 'no'
  MLC_REQUIRE_INSTALL: 'no'

deps:
- tags: detect,os
- enable_if_env:
    MLC_CUDA_FULL_TOOLKIT_INSTALL:
    - 'yes'
    MLC_HOST_OS_TYPE:
    - windows
  names:
  - compiler
  tags: get,cl

input_mapping:
  cudnn_tar_file: MLC_CUDNN_TAR_FILE_PATH
  cudnn_tar_path: MLC_CUDNN_TAR_FILE_PATH
  skip_sudo: CUDA_SKIP_SUDO
  skip_cudnn_install: MLC_CUDA_SKIP_CUDNN_INSTALL

new_env_keys:
- CUDA_HOME
- CUDA_PATH
- MLC_CUDA_*
- MLC_NVCC_*
- MLC_MLPERF_SUT_NAME_RUN_CONFIG_SUFFIX5
- +PATH
- +C_INCLUDE_PATH
- +CPLUS_INCLUDE_PATH
- +LD_LIBRARY_PATH
- +DYLD_FALLBACK_LIBRARY_PATH
- + LDFLAGS

prehook_deps:
- enable_if_env:
    MLC_REQUIRE_INSTALL:
    - 'yes'
  names:
  - install-cuda-prebuilt
  reuse_version: true
  tags: install,cuda,prebuilt
- enable_if_env:
    MLC_CUDA_PACKAGE_MANAGER_INSTALL:
    - 'yes'
  tags: get,generic-sys-util,_nvidia-cuda-toolkit

print_env_at_the_end:
  MLC_CUDA_PATH_LIB_CUDNN_EXISTS: ''
  MLC_CUDA_VERSION: ''
  MLC_CUDA_VERSION_STRING: ''
  MLC_NVCC_BIN_WITH_PATH: ''
  CUDA_HOME: ''

print_files_if_script_error:
- tmp-ver.out

variations:
  cudnn:
    env:
      MLC_CUDA_NEEDS_CUDNN: 'yes'
    post_deps:
    - names:
      - cudnn
      tags: get,nvidia,cudnn
      skip_if_env:
        MLC_CUDA_SKIP_CUDNN_INSTALL:
          - yes

  lib-only:
    env:
      MLC_CUDA_FULL_TOOLKIT_INSTALL: 'no'
      MLC_TMP_FILE_TO_CHECK_UNIX: libcudart.so
      MLC_TMP_FILE_TO_CHECK_WINDOWS: libcudart.dll
    group: installation-mode
  package-manager:
    env:
      MLC_CUDA_PACKAGE_MANAGER_INSTALL: 'yes'
  prebuilt:
    env:
      MLC_REQUIRE_INSTALL: 'yes'
  toolkit:
    default: true
    env:
      MLC_CUDA_FULL_TOOLKIT_INSTALL: 'yes'
      MLC_TMP_FILE_TO_CHECK_UNIX: nvcc
      MLC_TMP_FILE_TO_CHECK_WINDOWS: nvcc.exe
    group: installation-mode
