alias: install-onednn-from-src
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: Compiler automation
deps:
- tags: detect,os
- tags: detect,cpu
- names:
  - python
  - python3
  skip_if_env:
    MLC_CONDA_ENV:
    - 'yes'
  tags: get,python3
- env:
    MLC_GIT_CHECKOUT_PATH_ENV_NAME: MLC_ONEDNN_SRC_REPO_PATH
  extra_cache_tags: onednn,src,onednn-src,onednn-src-repo
  names:
  - onednn-src-repo
  tags: get,git,repo
  update_tags_from_env_with_prefix:
    _branch.:
    - MLC_GIT_CHECKOUT
    _repo.:
    - MLC_GIT_URL
    _sha.:
    - MLC_GIT_CHECKOUT_SHA
    _tag.:
    - MLC_GIT_CHECKOUT_TAG
env:
  MLC_GIT_URL: https://github.com/oneapi-src/oneDNN
name: Build oneDNN from sources
new_env_keys:
- MLC_ONEDNN_*
prehook_deps: []
sort: 1000
tags:
- install
- get
- src
- from.src
- onednn
- src-onednn
uid: fe3a652e315f4c8f
variations:
  branch.#:
    env:
      MLC_GIT_CHECKOUT: '#'
  for-intel-mlperf-inference-v3.1-bert:
    adr:
      conda-package:
        tags: _name.bert-pt
      oneddn-src-repo:
        tags: _norecurse-submodule
    base:
    - tag.v2.6
    env:
      MLC_CONDA_ENV: 'yes'
      MLC_FOR_INTEL_MLPERF_INFERENCE_BERT: 'yes'
  repo.#:
    env:
      MLC_GIT_URL: '#'
    group: repo
  repo.https://github.com/oneapi-src/oneDNN:
    default: true
    env:
      MLC_GIT_URL: https://github.com/oneapi-src/oneDNN
    group: repo
  sha.#:
    env:
      MLC_GIT_CHECKOUT_SHA: '#'
  tag.#:
    ad:
      onednn-src-repo:
        tags: _no-recurse-submodules,_full-history
    env:
      MLC_GIT_CHECKOUT_TAG: '#'
versions: {}
