alias: get-preprocessed-dataset-librispeech
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: AI/ML datasets
default_env:
  MLC_DATASET: kits19
  MLC_DATASET_DTYPE: fp32
deps:
- names:
  - python3
  - python
  tags: get,python3
- names:
  - original-dataset
  tags: get,dataset,speech-recognition,librispeech,original
- names:
  - inference-src
  tags: mlperf,mlcommons,inference,source,src
- tags: get,generic-python-lib,_sox
- tags: get,generic-python-lib,_pandas
- tags: get,generic-python-lib,_tqdm
- tags: get,sys-util,generic,_sox
input_mapping:
  dir: MLC_DATASET_PREPROCESSED_PATH
  threads: MLC_NUM_PREPROCESS_THREADS
new_env_keys:
- MLC_DATASET_*
tags:
- get
- dataset
- speech-recognition
- librispeech
- preprocessed
uid: e9f62fc969d5483a
variations:
  '1':
    adr:
      original-dataset:
        tags: _1
    env:
      MLC_DATASET_SIZE: '1'
    group: dataset-count
  '5':
    adr:
      original-dataset:
        tags: _5
    env:
      MLC_DATASET_SIZE: '5'
    group: dataset-count
  '50':
    adr:
      original-dataset:
        tags: _50
    env:
      MLC_DATASET_SIZE: '50'
    group: dataset-count
  '500':
    adr:
      original-dataset:
        tags: _500
    env:
      MLC_DATASET_SIZE: '500'
    group: dataset-count
  calibration:
    add_deps:
      original-dataset:
        tags: _calibration
    env:
      MLC_DATASET_PATH: <<<MLC_CALIBRATION_DATASET_PATH>>>
    group: dataset-type
  fp32:
    default: true
    env:
      MLC_DATASET_DTYPE: fp32
    group: dataset-precision
  full:
    adr:
      original-dataset:
        tags: _full
    env:
      MLC_DATASET_SIZE: ''
    group: dataset-count
  int8:
    env:
      MLC_DATASET_DTYPE: int8
    group: dataset-precision
  validation:
    add_deps:
      original-dataset:
        tags: validation
    default: true
    group: dataset-type
