alias: install-aws-cli
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: Cloud automation
deps:
- tags: detect,os
env:
  MLC_CURL_URL: https://awscli.amazonaws.com/awscli-exe-[OS]-[PLATFORM].zip
post_deps:
- skip_if_env:
    MLC_REQUIRE_INSTALL:
    - 'yes'
  tags: get,aws-cli
tags:
- install
- script
- aws-cli
- aws
- cli
uid: 4d3efd333c3f4d36
