alias: get-ml-model-mobilenet
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: AI/ML models
default_env:
  MLC_ML_MODEL: mobilenet
  MLC_ML_MODEL_DATASET: imagenet2012-val
  MLC_ML_MODEL_INPUTS_DATA_TYPE: fp32
  MLC_ML_MODEL_MOBILENET_NAME_SUFFIX: ''
  MLC_ML_MODEL_RETRAINING: 'no'
  MLC_ML_MODEL_WEIGHTS_DATA_TYPE: fp32
  MLC_ML_MODEL_WEIGHT_TRANSFORMATIONS: 'no'
new_env_keys:
- MLC_ML_MODEL_*
- MLC_DATASET_PREPROCESSED_IMAGENET_DEP_TAGS
print_env_at_the_end:
  MLC_ML_MODEL_FILE_WITH_PATH: Path to the ML model
tags:
- get
- ml-model
- mobilenet
- raw
- ml-model-mobilenet
- image-classification
uid: ce46675a3ab249e4
variations:
  fp32:
    default: true
    env:
      MLC_ML_MODEL_INPUTS_DATA_TYPE: fp32
      MLC_ML_MODEL_MOBILENET_PRECISION: float
      MLC_ML_MODEL_PRECISION: fp32
      MLC_ML_MODEL_WEIGHTS_DATA_TYPE: fp32
    group: precision
  from.google:
    env:
      MLC_DOWNLOAD_SOURCE: google
    group: source
  from.zenodo:
    env:
      MLC_DOWNLOAD_SOURCE: zenodo
    group: source
  int8:
    base:
    - quantized_
    env:
      MLC_ML_MODEL_INPUTS_DATA_TYPE: int8
      MLC_ML_MODEL_MOBILENET_PRECISION: int8
      MLC_ML_MODEL_PRECISION: int8
      MLC_ML_MODEL_WEIGHTS_DATA_TYPE: int8
    group: precision
  large:
    env:
      MLC_ML_MODEL_MOBILENET_KIND: large
    group: kind
  large-minimalistic:
    env:
      MLC_ML_MODEL_MOBILENET_KIND: large-minimalistic
    group: kind
  multiplier-0.25:
    env:
      MLC_ML_MODEL_MOBILENET_MULTIPLIER: '0.25'
      MLC_ML_MODEL_MOBILENET_MULTIPLIER_PERCENTAGE: '25'
    group: multiplier
  multiplier-0.35:
    env:
      MLC_ML_MODEL_MOBILENET_MULTIPLIER: '0.35'
      MLC_ML_MODEL_MOBILENET_MULTIPLIER_PERCENTAGE: '35'
    group: multiplier
  multiplier-0.5:
    env:
      MLC_ML_MODEL_MOBILENET_MULTIPLIER: '0.5'
      MLC_ML_MODEL_MOBILENET_MULTIPLIER_PERCENTAGE: '50'
    group: multiplier
  multiplier-0.75:
    env:
      MLC_ML_MODEL_MOBILENET_MULTIPLIER: '0.75'
      MLC_ML_MODEL_MOBILENET_MULTIPLIER_PERCENTAGE: '75'
    group: multiplier
  multiplier-1.0:
    env:
      MLC_ML_MODEL_MOBILENET_MULTIPLIER: '1.0'
      MLC_ML_MODEL_MOBILENET_MULTIPLIER_PERCENTAGE: '100'
    group: multiplier
  onnx:
    env:
      MLC_ML_MODEL_DATA_LAYOUT: NCHW
      MLC_ML_MODEL_FRAMEWORK: onnx
    group: framework
  onnx,fp32,v1:
    env:
      MLC_ML_MODEL_INPUT_LAYER_NAME: input:0
      MLC_ML_MODEL_NORMALIZE_DATA: 'yes'
      MLC_ML_MODEL_OUTPUT_LAYER_NAME: MobilenetV1/Predictions/Reshape_1:0
      MLC_ML_MODEL_SUBTRACT_MEANS: 'no'
      MLC_ML_MODEL_VER: '1_1.0_224'
  onnx,int8,v1:
    env:
      MLC_ML_MODEL_FILE: mobilenet_sym_no_bn.onnx
      MLC_ML_MODEL_GIVEN_CHANNEL_MEANS: 128.0 128.0 128.0
      MLC_ML_MODEL_INPUT_LAYER_NAME: '0'
      MLC_ML_MODEL_NORMALIZE_DATA: 'no'
      MLC_ML_MODEL_OUTPUT_LAYER_NAME: '169'
      MLC_ML_MODEL_SUBTRACT_MEANS: 'yes'
      MLC_ML_MODEL_VER: 1_1.0_224_quant
      MLC_PACKAGE_URL: https://zenodo.org/record/3353417/files/Quantized%20MobileNet.zip
      MLC_UNZIP: 'yes'
  onnx,opset-11,fp32,v1:
    env:
      MLC_PACKAGE_URL: https://zenodo.org/record/4735651/files/mobilenet_v1_1.0_224.onnx
  onnx,opset-8,fp32,v1:
    env:
      MLC_PACKAGE_URL: https://zenodo.org/record/3157894/files/mobilenet_v1_1.0_224.onnx
  opset-11:
    env:
      MLC_ML_MODEL_ONNX_OPSET: '11'
    group: opset-version
  opset-8:
    env:
      MLC_ML_MODEL_ONNX_OPSET: '8'
    group: opset-version
  quantized_:
    env:
      MLC_ML_MODEL_MOBILENET_NAME_SUFFIX: _quant
      MLC_ML_MODEL_WEIGHT_TRANSFORMATIONS: 'yes'
  resolution-128:
    env:
      MLC_DATASET_PREPROCESSED_IMAGENET_DEP_TAGS: _resolution.128
      MLC_ML_MODEL_IMAGE_HEIGHT: '128'
      MLC_ML_MODEL_IMAGE_WIDTH: '128'
      MLC_ML_MODEL_MOBILENET_RESOLUTION: '128'
    group: resolution
  resolution-160:
    env:
      MLC_DATASET_PREPROCESSED_IMAGENET_DEP_TAGS: _resolution.160
      MLC_ML_MODEL_IMAGE_HEIGHT: '160'
      MLC_ML_MODEL_IMAGE_WIDTH: '160'
      MLC_ML_MODEL_MOBILENET_RESOLUTION: '160'
    group: resolution
  resolution-192:
    env:
      MLC_DATASET_PREPROCESSED_IMAGENET_DEP_TAGS: _resolution.192
      MLC_ML_MODEL_IMAGE_HEIGHT: '192'
      MLC_ML_MODEL_IMAGE_WIDTH: '192'
      MLC_ML_MODEL_MOBILENET_RESOLUTION: '192'
    group: resolution
  resolution-224:
    env:
      MLC_DATASET_PREPROCESSED_IMAGENET_DEP_TAGS: _resolution.224
      MLC_ML_MODEL_IMAGE_HEIGHT: '224'
      MLC_ML_MODEL_IMAGE_WIDTH: '224'
      MLC_ML_MODEL_MOBILENET_RESOLUTION: '224'
    group: resolution
  small:
    env:
      MLC_ML_MODEL_MOBILENET_KIND: small
    group: kind
  small-minimalistic:
    default_variations:
      precision: fp32
    env:
      MLC_ML_MODEL_MOBILENET_KIND: small-minimalistic
    group: kind
  tf:
    default: true
    default_variations:
      source: from.google
    env:
      MLC_ML_MODEL_DATA_LAYOUT: NHWC
      MLC_ML_MODEL_INPUT_LAYER_NAME: input
      MLC_ML_MODEL_NORMALIZE_DATA: 'yes'
      MLC_ML_MODEL_SUBTRACT_MEANS: 'no'
    group: framework
  tf,fp32,v1,resolution-224,multiplier-1.0:
    env:
      MLC_ML_MODEL_ACCURACY: '71.676'
  tf,from.google,v1:
    env:
      MLC_PACKAGE_URL: http://download.tensorflow.org/models/mobilenet_v1_2018_08_02/mobilenet_v1_<<<MLC_ML_MODEL_MOBILENET_MULTIPLIER>>>_<<<MLC_ML_MODEL_MOBILENET_RESOLUTION>>><<<MLC_ML_MODEL_MOBILENET_NAME_SUFFIX>>>.tgz
      MLC_UNTAR: 'yes'
  tf,from.google,v2,fp32:
    env:
      MLC_ML_MODEL_FILE: mobilenet_v2_<<<MLC_ML_MODEL_MOBILENET_MULTIPLIER>>>_<<<MLC_ML_MODEL_MOBILENET_RESOLUTION>>>.tflite
      MLC_ML_MODEL_WEIGHTS_FILE: mobilenet_v2_<<<MLC_ML_MODEL_MOBILENET_MULTIPLIER>>>_<<<MLC_ML_MODEL_MOBILENET_RESOLUTION>>>.ckpt.data-00000-of-00001
      MLC_PACKAGE_URL: https://storage.googleapis.com/mobilenet_v2/checkpoints/mobilenet_v2_<<<MLC_ML_MODEL_MOBILENET_MULTIPLIER>>>_<<<MLC_ML_MODEL_MOBILENET_RESOLUTION>>>.tgz
      MLC_UNTAR: 'yes'
  tf,from.google,v2,quantized_:
    env:
      MLC_EXTRACT_FOLDER: v2_<<<MLC_ML_MODEL_MOBILENET_RESOLUTION>>>_<<<MLC_ML_MODEL_MOBILENET_MULTIPLIER_PERCENTAGE>>>
      MLC_ML_MODEL_FILE: model.tflite
      MLC_ML_MODEL_WEIGHTS_FILE: <<<MLC_ML_MODEL_MOBILENET_NAME_PREFIX>>>_v2_<<<MLC_ML_MODEL_MOBILENET_RESOLUTION>>>_<<<MLC_ML_MODEL_MOBILENET_MULTIPLIER_PERCENTAGE>>>.ckpt.data-00000-of-00001
      MLC_PACKAGE_URL: https://storage.googleapis.com/mobilenet_v2/checkpoints/<<<MLC_ML_MODEL_MOBILENET_NAME_PREFIX>>>_v2_<<<MLC_ML_MODEL_MOBILENET_RESOLUTION>>>_<<<MLC_ML_MODEL_MOBILENET_MULTIPLIER_PERCENTAGE>>>.tgz
      MLC_UNTAR: 'yes'
  tf,from.google,v3:
    env:
      MLC_EXTRACT_FOLDER: v3-<<<MLC_ML_MODEL_MOBILENET_KIND>>>_<<<MLC_ML_MODEL_MOBILENET_RESOLUTION>>>_<<<MLC_ML_MODEL_MOBILENET_MULTIPLIER>>>_<<<MLC_ML_MODEL_MOBILENET_PRECISION>>>
      MLC_ML_MODEL_FILE: v3-<<<MLC_ML_MODEL_MOBILENET_KIND>>>_<<<MLC_ML_MODEL_MOBILENET_RESOLUTION>>>_<<<MLC_ML_MODEL_MOBILENET_MULTIPLIER>>>_<<<MLC_ML_MODEL_MOBILENET_PRECISION>>>.tflite
      MLC_PACKAGE_URL: https://storage.googleapis.com/mobilenet_v3/checkpoints/v3-<<<MLC_ML_MODEL_MOBILENET_KIND>>>_<<<MLC_ML_MODEL_MOBILENET_RESOLUTION>>>_<<<MLC_ML_MODEL_MOBILENET_MULTIPLIER>>>_<<<MLC_ML_MODEL_MOBILENET_PRECISION>>>.tgz
      MLC_UNTAR: 'yes'
  tf,from.zenodo,v1:
    env:
      MLC_PACKAGE_URL: https://zenodo.org/record/2269307/files/mobilenet_v1_<<<MLC_ML_MODEL_MOBILENET_MULTIPLIER>>>_<<<MLC_ML_MODEL_MOBILENET_RESOLUTION>>><<<MLC_ML_MODEL_MOBILENET_NAME_SUFFIX>>>.tgz
      MLC_UNTAR: 'yes'
  tf,int8,v1,resolution-224,multiplier-1.0:
    env:
      MLC_ML_MODEL_ACCURACY: '70.762'
  tf,v1:
    env:
      MLC_ML_MODEL_FILE: mobilenet_v1_<<<MLC_ML_MODEL_MOBILENET_MULTIPLIER>>>_<<<MLC_ML_MODEL_MOBILENET_RESOLUTION>>><<<MLC_ML_MODEL_MOBILENET_NAME_SUFFIX>>>.tflite
      MLC_ML_MODEL_OUTPUT_LAYER_NAME: MobilenetV1/Predictions/Reshape_1
      MLC_ML_MODEL_VER: 1_<<<MLC_ML_MODEL_MOBILENET_MULTIPLIER>>>_<<<MLC_ML_MODEL_MOBILENET_RESOLUTION>>><<<MLC_ML_MODEL_MOBILENET_NAME_SUFFIX>>>_2018_08_02
      MLC_ML_MODEL_WEIGHTS_FILE: mobilenet_v1_<<<MLC_ML_MODEL_MOBILENET_MULTIPLIER>>>_<<<MLC_ML_MODEL_MOBILENET_RESOLUTION>>><<<MLC_ML_MODEL_MOBILENET_NAME_SUFFIX>>>.ckpt.data-00000-of-00001
  tf,v1,fp32:
    env:
      MLC_ML_MODEL_MOBILENET_NAME_PREFIX: ''
  tf,v1,int8:
    env:
      MLC_ML_MODEL_MOBILENET_NAME_SUFFIX: _quant
  tf,v1,uint8:
    env:
      MLC_ML_MODEL_MOBILENET_NAME_SUFFIX: _quant
  tf,v2,fp32:
    env:
      MLC_ML_MODEL_MOBILENET_NAME_PREFIX: ''
      MLC_ML_MODEL_OUTPUT_LAYER_NAME: MobilenetV2/Predictions/Reshape_1
      MLC_ML_MODEL_VER: 2_<<<MLC_ML_MODEL_MOBILENET_MULTIPLIER>>>_<<<MLC_ML_MODEL_MOBILENET_RESOLUTION>>>
  tf,v2,int8:
    env:
      MLC_ML_MODEL_MOBILENET_NAME_PREFIX: quantized
      MLC_ML_MODEL_OUTPUT_LAYER_NAME: MobilenetV2/Predictions/Softmax
      MLC_ML_MODEL_VER: 2_<<<MLC_ML_MODEL_MOBILENET_MULTIPLIER>>>_<<<MLC_ML_MODEL_MOBILENET_RESOLUTION>>>
  tf,v2,uint8:
    env:
      MLC_ML_MODEL_MOBILENET_NAME_PREFIX: quantized
      MLC_ML_MODEL_OUTPUT_LAYER_NAME: MobilenetV2/Predictions/Softmax
      MLC_ML_MODEL_VER: 2_<<<MLC_ML_MODEL_MOBILENET_MULTIPLIER>>>_<<<MLC_ML_MODEL_MOBILENET_RESOLUTION>>>
  tf,v3:
    env:
      MLC_ML_MODEL_OUTPUT_LAYER_NAME: MobilenetV3/Predictions/Softmax
      MLC_ML_MODEL_VER: 3_<<<MLC_ML_MODEL_MOBILENET_KIND>>>_<<<MLC_ML_MODEL_MOBILENET_RESOLUTION>>>
  tflite:
    base:
    - tf
  uint8:
    base:
    - quantized_
    env:
      MLC_ML_MODEL_INPUTS_DATA_TYPE: uint8
      MLC_ML_MODEL_MOBILENET_PRECISION: uint8
      MLC_ML_MODEL_PRECISION: uint8
      MLC_ML_MODEL_WEIGHTS_DATA_TYPE: uint8
    group: precision
  v1:
    default_variations:
      multiplier: multiplier-1.0
      resolution: resolution-224
    env:
      MLC_ML_MODEL_FULL_NAME: mobilenet-v1-precision_<<<MLC_ML_MODEL_MOBILENET_PRECISION>>>-<<<MLC_ML_MODEL_MOBILENET_MULTIPLIER>>>-<<<MLC_ML_MODEL_MOBILENET_RESOLUTION>>>
      MLC_ML_MODEL_MOBILENET_VERSION: '1'
    group: version
  v2:
    default_variations:
      multiplier: multiplier-1.0
      resolution: resolution-224
    env:
      MLC_ML_MODEL_FULL_NAME: mobilenet-v2-precision_<<<MLC_ML_MODEL_MOBILENET_PRECISION>>>-<<<MLC_ML_MODEL_MOBILENET_MULTIPLIER>>>-<<<MLC_ML_MODEL_MOBILENET_RESOLUTION>>>
      MLC_ML_MODEL_MOBILENET_VERSION: '2'
      MLC_ML_MODEL_VER: '2'
    group: version
  v3:
    default: true
    default_variations:
      multiplier: multiplier-1.0
      resolution: resolution-224
    env:
      MLC_ML_MODEL_FULL_NAME: mobilenet-v3-precision_<<<MLC_ML_MODEL_MOBILENET_PRECISION>>>-<<<MLC_ML_MODEL_MOBILENET_KIND>>>-<<<MLC_ML_MODEL_MOBILENET_RESOLUTION>>>
      MLC_ML_MODEL_MOBILENET_VERSION: '3'
      MLC_ML_MODEL_VER: '3'
    group: version
