alias: install-bazel
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: Detection or installation of tools and artifacts
default_version: 7.0.2
deps:
- tags: detect,os
env:
  MLC_WGET_URL: https://github.com/bazelbuild/bazel/releases/download/[VERSION]/bazel-[VERSION]-installer-[OS]-[PLATFORM].sh
new_env_keys:
- MLC_BAZEL_*
post_deps:
- skip_if_env:
    MLC_REQUIRE_INSTALL:
    - 'yes'
  tags: get,bazel
tags:
- install
- script
- bazel
uid: dfd3d2bf5b764175
