alias: get-mlperf-inference-results-dir
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: MLPerf benchmark support
deps: []
docker:
  run: false
input_description: {}
input_mapping:
  results_dir: MLC_MLPERF_INFERENCE_RESULTS_DIR
new_env_keys:
- MLC_MLPERF_INFERENCE_RESULTS_DIR
- MLC_MLPERF_INFERENCE_RESULTS_VERSION
new_state_keys: []
post_deps: []
posthook_deps: []
prehook_deps: []
tags:
- get
- mlperf
- inference
- local
- results
- dir
- directory
uid: 84f3c5aad5e1444b
variations:
  path.#:
    MLC_MLPERF_INFERENCE_RESULTS_DIR: '#'
  version.#:
    env:
      MLC_MLPERF_INFERENCE_RESULTS_VERSION: '#'
    group: version
  version.4_1:
    env:
      MLC_MLPERF_INFERENCE_RESULTS_VERSION: '4_1'
    group: version
  version.4_1-dev:
    default: true
    env:
      MLC_MLPERF_INFERENCE_RESULTS_VERSION: 4_1-dev
    group: version
versions: {}
