alias: get-aws-cli
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: Cloud automation
clean_files: []
new_env_keys:
- MLC_AWS_*
prehook_deps:
- enable_if_env:
    MLC_REQUIRE_INSTALL:
    - 'yes'
  reuse_version: true
  tags: install,aws-cli
tags:
- get
- aws-cli
- aws
- cli
uid: dad67944229942a3
