alias: get-ml-model-efficientnet-lite
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: AI/ML models
default_env:
  MLC_ML_MODEL_INPUTS_DATA_TYPE: fp32
  MLC_ML_MODEL_PRECISION: fp32
  MLC_ML_MODEL_WEIGHTS_DATA_TYPE: fp32
env:
  MLC_EXTRACT_FOLDER: efficientnet-<<<MLC_ML_MODEL_EFFICIENTNET_LITE_KIND>>>
  MLC_ML_MODEL: efficientnet-lite
  MLC_ML_MODEL_DATASET: imagenet2012-val
  MLC_ML_MODEL_DATA_LAYOUT: NHWC
  MLC_ML_MODEL_FILE: efficientnet-<<<MLC_ML_MODEL_EFFICIENTNET_LITE_KIND>>>-<<<MLC_ML_MODEL_EFFICIENTNET_LITE_PRECISION>>>.tflite
  MLC_ML_MODEL_FULL_NAME: efficientnet-<<<MLC_ML_MODEL_EFFICIENTNET_LITE_PRECISION>>>-<<<MLC_ML_MODEL_EFFICIENTNET_LITE_KIND>>>
  MLC_ML_MODEL_GIVEN_CHANNEL_MEANS: ''
  MLC_ML_MODEL_INPUT_LAYER_NAME: images
  MLC_ML_MODEL_INPUT_SHAPES: '\"input\": (BATCH_SIZE, 224, 224, 3)'
  MLC_ML_MODEL_MOBILENET_NAME_SUFFIX: ''
  MLC_ML_MODEL_NORMALIZE_DATA: 'yes'
  MLC_ML_MODEL_OUTPUT_LAYER_NAME: Softmax
  MLC_ML_MODEL_RETRAINING: 'no'
  MLC_ML_MODEL_SUBTRACT_MEANS: '0'
  MLC_ML_MODEL_WEIGHTS_ARE_CHECKPOINTS: 'yes'
  MLC_ML_MODEL_WEIGHTS_FILE: model.ckpt.data-00000-of-00001
  MLC_ML_MODEL_WEIGHT_TRANSFORMATIONS: 'no'
  MLC_PACKAGE_URL: https://storage.googleapis.com/cloud-tpu-checkpoints/efficientnet/lite/efficientnet-<<<MLC_ML_MODEL_EFFICIENTNET_LITE_KIND>>>.tar.gz
  MLC_UNTAR: 'yes'
new_env_keys:
- MLC_ML_MODEL_*
- MLC_DATASET_PREPROCESSED_IMAGENET_DEP_TAGS
print_env_at_the_end:
  MLC_ML_MODEL_FILE_WITH_PATH: Path to the ML model
tags:
- get
- ml-model
- efficientnet
- raw
- ml-model-efficientnet
- ml-model-efficientnet-lite
- lite
- tflite
- image-classification
uid: 1041f681977d4b7c
valid_variation_combinations:
- - lite0
  - resolution-224
- - lite1
  - resolution-240
- - lite2
  - resolution-260
- - lite3
  - resolution-280
- - lite4
  - resolution-300
variations:
  fp32:
    default: true
    env:
      MLC_ML_MODEL_EFFICIENTNET_LITE_PRECISION: fp32
      MLC_ML_MODEL_INPUTS_DATA_TYPE: fp32
      MLC_ML_MODEL_PRECISION: fp32
      MLC_ML_MODEL_WEIGHTS_DATA_TYPE: fp32
    group: precision
  int8:
    alias: uint8
  lite0:
    base:
    - resolution-224
    default: true
    env:
      MLC_ML_MODEL_EFFICIENTNET_LITE_KIND: lite0
    group: kind
  lite1:
    base:
    - resolution-240
    env:
      MLC_ML_MODEL_EFFICIENTNET_LITE_KIND: lite1
    group: kind
  lite2:
    base:
    - resolution-260
    env:
      MLC_ML_MODEL_EFFICIENTNET_LITE_KIND: lite2
    group: kind
  lite3:
    base:
    - resolution-280
    env:
      MLC_ML_MODEL_EFFICIENTNET_LITE_KIND: lite3
    group: kind
  lite4:
    base:
    - resolution-300
    env:
      MLC_ML_MODEL_EFFICIENTNET_LITE_KIND: lite4
    group: kind
  resolution-224:
    default: true
    env:
      MLC_DATASET_PREPROCESSED_IMAGENET_DEP_TAGS: _resolution.224
      MLC_ML_MODEL_IMAGE_HEIGHT: '224'
      MLC_ML_MODEL_IMAGE_WIDTH: '224'
      MLC_ML_MODEL_MOBILENET_RESOLUTION: '224'
    group: resolution
  resolution-240:
    env:
      MLC_DATASET_PREPROCESSED_IMAGENET_DEP_TAGS: _resolution.240
      MLC_ML_MODEL_IMAGE_HEIGHT: '240'
      MLC_ML_MODEL_IMAGE_WIDTH: '240'
      MLC_ML_MODEL_MOBILENET_RESOLUTION: '240'
    group: resolution
  resolution-260:
    env:
      MLC_DATASET_PREPROCESSED_IMAGENET_DEP_TAGS: _resolution.260
      MLC_ML_MODEL_IMAGE_HEIGHT: '260'
      MLC_ML_MODEL_IMAGE_WIDTH: '260'
      MLC_ML_MODEL_MOBILENET_RESOLUTION: '260'
    group: resolution
  resolution-280:
    env:
      MLC_DATASET_PREPROCESSED_IMAGENET_DEP_TAGS: _resolution.280
      MLC_ML_MODEL_IMAGE_HEIGHT: '280'
      MLC_ML_MODEL_IMAGE_WIDTH: '280'
      MLC_ML_MODEL_MOBILENET_RESOLUTION: '280'
    group: resolution
  resolution-300:
    env:
      MLC_DATASET_PREPROCESSED_IMAGENET_DEP_TAGS: _resolution.300
      MLC_ML_MODEL_IMAGE_HEIGHT: '300'
      MLC_ML_MODEL_IMAGE_WIDTH: '300'
      MLC_ML_MODEL_MOBILENET_RESOLUTION: '300'
    group: resolution
  tflite: {}
  uint8:
    env:
      MLC_ML_MODEL_EFFICIENTNET_LITE_PRECISION: int8
      MLC_ML_MODEL_INPUTS_DATA_TYPE: uint8
      MLC_ML_MODEL_PRECISION: uint8
      MLC_ML_MODEL_WEIGHTS_DATA_TYPE: uint8
    group: precision
