alias: get-dataset-openorca
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: AI/ML datasets
category_sort: 8500
default_env:
  MLC_DATASET_CALIBRATION: 'no'
deps:
- env:
    MLC_GIT_CHECKOUT_PATH_ENV_NAME: MLC_DATASET_OPENORCA_PATH
  extra_cache_tags: openorca,repo,src
  force_env_keys:
  - MLC_GIT_*
  names:
  - openorca-src
  tags: get,git,repo,_lfs,_repo.https://huggingface.co/datasets/Open-Orca/OpenOrca
  force_env_keys:
    - MLC_OUTDIRNAME  
env:
  MLC_DATASET: OPENORCA
new_env_keys:
- MLC_DATASET_*
tags:
- get
- dataset
- openorca
- language-processing
- original
uid: 9252c4d90d5940b7
variations:
  '500':
    env:
      MLC_DATASET_SIZE: '500'
    group: size
  '60':
    env:
      MLC_DATASET_SIZE: '60'
    group: size
  calibration:
    env:
      MLC_DATASET_CALIBRATION: 'yes'
    group: dataset-type
  full:
    default: true
    env:
      MLC_DATASET_SIZE: '24576'
    group: size
  size.#:
    env:
      MLC_DATASET_SIZE: '#'
    group: size
  validation:
    default: true
    env:
      MLC_DATASET_CALIBRATION: 'no'
    group: dataset-type
