alias: get-conda
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: DevOps automation
clean_files: []
deps:
- tags: detect,os
new_env_keys:
- +PATH
- +LD_LIBRARY_PATH
- +LIBRARY_PATH
- MLC_CONDA_PREFIX
- CONDA_PREFIX
- MLC_CONDA_BIN_PATH
- MLC_CONDA_BIN_WITH_PATH
- MLC_CONDA_LIB_PATH
tags:
- get
- conda
- get-conda
uid: 6600115f41324c7b
variations:
  name.#:
    adr:
      conda-package:
        tags: _name.#
    env:
      MLC_CONDA_PREFIX_NAME: '#'
  python-3.#:
    env:
      MLC_CONDA_PYTHON_VERSION: 3.#
    group: conda-python
  python-3.8:
    env:
      MLC_CONDA_PYTHON_VERSION: '3.8'
    group: conda-python
