alias: get-mlperf-training-src
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: MLPerf benchmark support
default_env:
  MLC_GIT_CHECKOUT: master
  MLC_GIT_CHECKOUT_FOLDER: training
  MLC_GIT_DEPTH: --depth 4
  MLC_GIT_PATCH: 'no'
  MLC_GIT_RECURSE_SUBMODULES: ' --recurse-submodules'
default_version: master
new_env_keys:
- MLC_MLPERF_TRAINING_*
- MLC_MLPERF_TRAINING_LAST_RELEASE
- +PYTHONPATH
prehook_deps:
- env:
    MLC_GIT_CHECKOUT_PATH_ENV_NAME: MLC_MLPERF_TRAINING_SOURCE
  extra_cache_tags: mlperf,training,src
  force_env_keys:
  - MLC_GIT_*
  names:
  - mlperf-training-repo
  tags: get,git,repo
  update_tags_from_env_with_prefix:
    _branch.:
    - MLC_GIT_CHECKOUT
    _repo.:
    - MLC_GIT_URL
    _sha.:
    - MLC_GIT_SHA
    _tag.:
    - MLC_GIT_CHECKOUT_TAG
tags:
- get
- src
- source
- training
- training-src
- training-source
- mlperf
- mlcommons
uid: dc440bd88e794a28
variations:
  branch.#:
    env:
      MLC_GIT_CHECKOUT: '#'
    group: checkout
  cknowledge:
    default: true
    env:
      MLC_GIT_URL: https://github.com/cknowledge/training.git
    group: src
  full-history:
    env:
      MLC_GIT_DEPTH: ''
    group: git-history
  mlcommons:
    env:
      MLC_GIT_URL: https://github.com/mlcommons/training.git
    group: src
  no-recurse-submodules:
    env:
      MLC_GIT_RECURSE_SUBMODULES: ''
  nvidia-retinanet:
    base:
    - patch
    env:
      MLC_GIT_PATCH_FILENAMES: nvidia-retinanet.patch,cpu_load.patch
  patch:
    env:
      MLC_GIT_PATCH: 'yes'
  repo.#:
    env:
      MLC_GIT_URL: '#'
    group: repo
  sha.#:
    env:
      MLC_GIT_SHA: '#'
    group: checkout
  short-history:
    default: true
    env:
      MLC_GIT_DEPTH: --depth 5
    group: git-history
  tag.#:
    env:
      MLC_GIT_CHECKOUT_TAG: '#'
    group: checkout
versions:
  custom:
    env:
      MLC_MLPERF_LAST_RELEASE: custom
  master:
    env:
      MLC_MLPERF_LAST_RELEASE: v3.1
