alias: get-aocl
automation_alias: script
automation_uid: 5b4e0237da074764
cache: 'true'
category: Compiler automation
default_version: '4.0'
deps:
- tags: get,generic,sys-util,_libmpfr-dev
- tags: get,generic-python-lib,_scons
- force_env_keys:
  - MLC_GIT_CHECKOUT
  tags: get,git,_repo.https://github.com/amd/aocl-libm-ose
new_env_keys:
- MLC_AOCL_BUILD_PATH
- MLC_AOCL_SRC_PATH
- MLC_AOCL_LIB_PATH
- +LD_LIBRARY_PATH
- +LIBRARY_PATH
tags:
- get
- lib
- aocl
- amd-optimized
- amd
uid: a65d3088f57d413d
variations: {}
versions:
  '4.0':
    env:
      MLC_GIT_CHECKOUT: aocl-4.0
  master:
    env:
      MLC_GIT_CHECKOUT: master
