uid: 7cd1d9b7e8af4788
alias: get-preprocessed-dataset-squad

automation_alias: script
automation_uid: 5b4e0237da074764

cache: true

category: AI/ML datasets

deps:
  - tags: get,python3
    names:
      - python
      - python3
  - tags: get,mlperf,inference,src
    names:
      - inference-src
  - tags: get,squad,dataset,original
    names:
      - squad-dataset
  - tags: get,squad,vocab
    names:
      - squad-vocab
  - tags: get,generic-python-lib,_package.tokenization
  - tags: get,generic-python-lib,_package.transformers
  - tags: get,generic-python-lib,_package.tensorflow

env:
  MLC_DATASET_MAX_QUERY_LENGTH: 64

new_env_keys:
  - MLC_DATASET_SQUAD_TOKENIZED_*

tags:
- get
- dataset
- preprocessed
- tokenized
- squad

variations:
  calib1:
    group: calibration-set
    env:
      MLC_DATASET_SQUAD_CALIBRATION_SET: one
  calib2:
    group: calibration-set
    env:
      MLC_DATASET_SQUAD_CALIBRATION_SET: two
  no-calib:
    group: calibration-set
    default: true
    env:
      MLC_DATASET_SQUAD_CALIBRATION_SET: ''
  raw:
    group: raw
    default: true
    env:
      MLC_DATASET_RAW: "yes"
  pickle:
    group: raw
    env:
      MLC_DATASET_RAW: "no"
  seq-length.#:
    group: seq-length
    env:
      MLC_DATASET_MAX_SEQ_LENGTH: "#"
  seq-length.384:
    group: seq-length
    default: true
    env:
      MLC_DATASET_MAX_SEQ_LENGTH: 384
  doc-stride.#:
    group: doc-stride
    env:
      MLC_DATASET_DOC_STRIDE: "#"
  doc-stride.128:
    group: doc-stride
    default: true
    env:
      MLC_DATASET_DOC_STRIDE: 128
  packed:
    group: packing
    env:
      MLC_DATASET_SQUAD_PACKED: 'yes'
    deps:
      - tags: get,preprocessed,squad,_pickle
        env:
          MLC_DATASET_SQUAD_PACKED: ''
        inherit_variation_tags: true
        skip_inherit_variation_groups:
        - packing
