alias: prune-bert-models
automation_alias: script
automation_uid: 5b4e0237da074764
category: AI/ML optimization
default_env:
  MLC_BERT_PRUNE_CONSTRAINT: '0.5'
  MLC_BERT_PRUNE_MODEL_NAME: bert-large-uncased
  MLC_BERT_PRUNE_TASK: squad
  MLC_MODEL_ZOO_STUB: bert-large-uncased
deps:
- tags: get,python3
- tags: get,generic-python-lib,_numpy
- tags: get,generic-python-lib,_scipy
- tags: get,generic-python-lib,_cupy
- tags: get,generic-python-lib,_tqdm
- tags: get,generic-python-lib,_torch_cuda
- tags: get,generic-python-lib,_datasets
- tags: get,generic-python-lib,_transformers
- tags: get,generic-python-lib,_scikit-learn
- env:
    MLC_GIT_ENV_KEY: BERT_PRUNER_NEURIPS_2022
  tags: get,git,repo,_repo.https://github.com/cknowledge/retraining-free-pruning
- names:
  - get-model
  tags: get,ml-model,model,zoo,model-zoo,huggingface,_prune
input_mapping:
  constraint: MLC_BERT_PRUNE_CONSTRAINT
  output_dir: MLC_BERT_PRUNE_OUTPUT_DIR
tags:
- prune
- bert-models
- bert-prune
- prune-bert-models
uid: 76182d4896414216
variations:
  model.#:
    adr:
      get-model:
        tags: _model-stub.#
    env:
      MLC_BERT_PRUNE_MODEL_NAME: '#'
      MLC_MODEL_ZOO_STUB: '#'
  path.#:
    env:
      MLC_BERT_PRUNE_CKPT_PATH: '#'
  task.#:
    env:
      MLC_BERT_PRUNE_TASK: '#'
