alias: get-rocm
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: AI/ML frameworks
clean_files: []
new_env_keys:
- MLC_ROMLC_*
- +PATH
prehook_deps:
- enable_if_env:
    MLC_REQUIRE_INSTALL:
    - 'yes'
  reuse_version: true
  tags: install,rocm
tags:
- get
- rocm
- get-rocm
uid: 23a69f9477cb4dab
