alias: install-gflags-from-src
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: Compiler automation
deps:
- tags: detect,os
- tags: detect,cpu
- env:
    MLC_GIT_CHECKOUT_PATH_ENV_NAME: MLC_GFLAGS_SRC_REPO_PATH
  extra_cache_tags: gflags,src,gflags-src,gflags-src-repo
  names:
  - gflags-src-repo
  - gflags-src
  tags: get,git,repo
  update_tags_from_env_with_prefix:
    _branch.:
    - MLC_GIT_CHECKOUT
    _repo.:
    - MLC_GIT_URL
    _sha.:
    - MLC_GIT_CHECKOUT_SHA
    _tag.:
    - MLC_GIT_CHECKOUT_TAG
env: {}
name: Build gflags from sources
new_env_keys:
- MLC_GFLAGS_*
prehook_deps: []
sort: 1000
tags:
- install
- get
- src
- from.src
- gflags
- src-gflags
uid: f311366ff15e4cdf
variations:
  branch.#:
    env:
      MLC_GIT_CHECKOUT: '#'
  repo.#:
    env:
      MLC_GIT_URL: '#'
    group: repo
  repo.https://github.com/gflags/gflags:
    default: true
    env:
      MLC_GIT_URL: https://github.com/gflags/gflags
    group: repo
  sha.#:
    env:
      MLC_GIT_CHECKOUT_SHA: '#'
  tag.#:
    ad:
      gflags-src-repo:
        tags: _no-recurse-submodules,_full-history
    env:
      MLC_GIT_CHECKOUT_TAG: '#'
versions: {}
